---
sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  - docker --version
  - docker pull o2rproject/o2r-loader:latest
  - docker pull o2rproject/o2r-muncher:latest
  - docker pull o2rproject/o2r-meta:latest
  - docker pull o2rproject/containerit:geospatial
  - docker pull mongo:3.4
install:
  - npm install
before_script:
  - mkdir -p /tmp/o2r
  - docker run --name mongodb -d -p 27017:27017 mongo:3.4
  - docker run --name testloader  -d -p 8088:8088 --link mongodb:mongodb -v /tmp/o2r:/tmp/o2r -v /var/run/docker.sock:/var/run/docker.sock -e LOADER_MONGODB=mongodb://mongodb:27017 -e DEBUG=* o2rproject/o2r-loader:latest
  - docker run --name testmuncher -d -p 8080:8080 --link mongodb:mongodb -v /tmp/o2r:/tmp/o2r -v /var/run/docker.sock:/var/run/docker.sock -e MUNCHER_MONGODB=mongodb://mongodb:27017 -e DEBUG=* o2rproject/o2r-muncher:latest
  - docker build --tag transporter . --build-arg VERSION=travis
  - docker run --name testtransporter -d -p 8081:8081 --link mongodb:mongodb -v /tmp/o2r:/tmp/o2r -e TRANSPORTER_MONGODB=mongodb://mongodb:27017 -e DEBUG=* transporter
  - sleep 10
script:
  - DEBUG=* npm test
after_failure:
  - sleep 5
  - docker logs testloader
  - docker logs testmuncher
  - docker logs testtransporter
